variables:
  PYTHON_VER: '3.13'
  PYGNOME_PROJECT_ID: '7'
  APP_NETWORK: webgnome_net
  UPSTREAM_BRANCH: $CI_COMMIT_BRANCH
  PYGNOME_VER: develop
  LIBGOODS_VER: develop
  WEBGNOME_API_VER: fargate-migration
  WEBGNOME_CLIENT_VER: develop
  MY_SERVER_ROLE_TAG: 'gnome'
  LATEST_IMAGE: false

stages:
  - util
  - build
  - test
  - deploy
  - maintenance

.build_template: &build_definition
  stage: build
  image: docker:dind
  services:
    - docker:dind
  before_script:
    - unset DOCKER_AUTH_CONFIG
  script:
    - docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD}
      ${CI_REGISTRY}
    - >
      docker build \
        --build-arg git_commit_short_hash=${CI_COMMIT_SHORT_SHA} \
        --build-arg build_env=${TARGET_ENV} \
        --build-arg PYTHON_VER=${PYTHON_VER} \
        --build-arg PYGNOME_VER=${PYGNOME_VER} \
        --build-arg LIBGOODS_VER=${LIBGOODS_VER} \
        --build-arg WEBGNOME_API_VER=${WEBGNOME_API_VER} \
        --build-arg BUILD_KEY=${BUILD_KEY} \
        --no-cache \
        -f dockerfile.mono \
        -t "${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA}" .
    - docker push ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA}
    - echo "GCR_IMAGE=${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA}" >> build.env
  artifacts:
    reports:
      dotenv: build.env
  tags:
    - 'docker'
    - 'aws'
    - 'us-west-2'

.deploy_template: &deploy_definition
  stage: deploy
  image: docker:dind
  when: manual
  services:
    - docker:dind
  before_script:
    - unset DOCKER_AUTH_CONFIG
  script:
    - apk --update --no-cache add bash aws-cli
    # Pull image from GCR using GCR_IMAGE from previous job.
    - docker login -u "${CI_REGISTRY_USER}" -p "${CI_REGISTRY_PASSWORD}"
      "${CI_REGISTRY}"
    - echo "Pulling $GCR_IMAGE"
    - docker pull "$GCR_IMAGE"
    - docker logout "${CI_REGISTRY}"
    - aws ecr get-login-password --region "$AWS_DEFAULT_REGION" | docker login
      --username AWS --password-stdin "$ECR_REPO_URI"
    - docker tag "$GCR_IMAGE" "${ECR_REPO_URI}:latest"
    - docker tag "$GCR_IMAGE" "${ECR_REPO_URI}:$CI_COMMIT_SHORT_SHA"
    - echo "Pushing $GCR_IMAGE to ${ECR_REPO_URI}"
    - docker push "${ECR_REPO_URI}:latest"
    - docker push "${ECR_REPO_URI}:$CI_COMMIT_SHORT_SHA"
    - |
      for SERVICE in $FARGATE_SERVICES; do
        SERVICE_NAME=$(echo $SERVICE | awk -F: '{print $1}')
        SERVICE_COUNT=$(echo $SERVICE | awk -F: '{print $2}')
        aws ecs update-service --cluster "$FARGATE_CLUSTER" \
            --service "$SERVICE_NAME" \
            --desired-count "$SERVICE_COUNT" \
            --force-new-deployment --debug
      done
  tags:
    - 'docker'
    - 'aws'
    - 'us-west-2'

.dev: &dev_definition
  environment:
    name: dev
    url: https://gnome-dev.nos-orr.net
  variables:
    API_URL: https://gnome-dev.nos-orr.net
    TARGET_ENV: dev
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" # Skip for merge requests
      when: never
    - if: $CI_COMMIT_BRANCH == "fargate-migration"

.prod: &prod_definition
  environment:
    name: prod
    url: https://gnome.orr.noaa.gov
  variables:
    API_URL: https://gnome.orr.noaa.gov
    TARGET_ENV: prod
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" # Skip for merge requests
      when: never
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

Development Build Docker Image:
  <<: *build_definition
  <<: *dev_definition

Production Build Docker Image:
  <<: *build_definition
  <<: *prod_definition

Development Push to ECR and Update Fargate Service:
  <<: *deploy_definition
  <<: *dev_definition

Production Push to ECR and Update Fargate Service:
  <<: *deploy_definition
  <<: *prod_definition
