variables:
  PYTHON_VER: '3.13'
  # These version should be the "evergreen" targets for latest of everything
  PYGNOME_VER: develop
  LIBGOODS_VER: main
  PYGNOME_PROJECT_ID: '7'

stages:
  - build
  - test
  - deploy

.build_template: &build_definition
  stage: build
  image: docker:dind
  services:
    - docker:dind
  before_script:
    - unset DOCKER_AUTH_CONFIG
    - if [ -z "$WEBGNOME_API_VER"]; then
      WEBGNOME_API_VER=${CI_COMMMIT_REF_NAME}; fi
    - if [ -z "$WEBGNOME_CLIENT_VER"]; then WEBGNOME_CLIENT_VER="develop"; fi
  script:
    - docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD}
      ${CI_REGISTRY}
    - >
      docker build \
        --build-arg git_commit_short_hash=${CI_COMMIT_SHORT_SHA} \
        --build-arg build_env=${TARGET_ENV} \
        --build-arg PYTHON_VER=${PYTHON_VER} \
        --build-arg PYGNOME_VER=${PYGNOME_VER} \
        --build-arg LIBGOODS_VER=${LIBGOODS_VER} \
        --build-arg WEBGNOME_API_VER=${WEBGNOME_API_VER} \
        --build-arg WEBGNOME_CLIENT_VER=${WEBGNOME_CLIENT_VER} \
        --build-arg BUILD_KEY=${BUILD_KEY} \
        --target ${TARGET_ENV} \
        --no-cache \
        -f dockerfile.mono \
        -t "${IMAGE_NAME}" .
    - docker push ${IMAGE_NAME}
    - echo "GCR_IMAGE=${IMAGE_NAME}" >> build.env
  artifacts:
    reports:
      dotenv: build.env
  tags:
    - 'docker'
    - 'aws'
    - 'us-west-2'

.deploy_template: &deploy_definition
  stage: deploy
  image: docker:dind
  when: manual
  services:
    - docker:dind
  before_script:
    - unset DOCKER_AUTH_CONFIG
    - if [ -z "$WEBGNOME_API_VER"]; then
      WEBGNOME_API_VER=${CI_COMMMIT_REF_NAME}; fi
    - if [ -z "$WEBGNOME_CLIENT_VER"]; then WEBGNOME_CLIENT_VER="develop"; fi
  script:
    - apk --update --no-cache add bash aws-cli
    # Pull image from GCR using GCR_IMAGE from previous job.
    - docker login -u "${CI_REGISTRY_USER}" -p "${CI_REGISTRY_PASSWORD}"
      "${CI_REGISTRY}"
    - echo "Pulling $GCR_IMAGE"
    - docker pull "$GCR_IMAGE"
    - docker logout "${CI_REGISTRY}"
    - aws ecr get-login-password --region "$AWS_DEFAULT_REGION" | docker login
      --username AWS --password-stdin "$ECR_REPO_URI"
    - docker tag "$GCR_IMAGE" "${ECR_REPO_URI}:latest"
    - docker tag "$GCR_IMAGE" "${ECR_REPO_URI}:$CI_COMMIT_SHORT_SHA"
    - echo "Pushing $GCR_IMAGE to ${ECR_REPO_URI}"
    - docker push "${ECR_REPO_URI}:latest"
    - docker push "${ECR_REPO_URI}:$CI_COMMIT_SHORT_SHA"
    - |
      for SERVICE in $FARGATE_SERVICES; do
        SERVICE_NAME=$(echo $SERVICE | awk -F: '{print $1}')
        SERVICE_COUNT=$(echo $SERVICE | awk -F: '{print $2}')
        aws ecs update-service --cluster "$FARGATE_CLUSTER" \
            --service "$SERVICE_NAME" \
            --desired-count "$SERVICE_COUNT" \
            --force-new-deployment --debug
      done
  tags:
    - 'docker'
    - 'aws'
    - 'us-west-2'

.dev: &dev_definition
  environment:
    name: dev
    url: https://gnome-dev.nos-orr.net
  variables:
    API_URL: https://gnome-dev.nos-orr.net
    TARGET_ENV: dev
    IMAGE_NAME: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA}-c-${WEBGNOME_CLIENT_VER}-p-${PYGNOME_VER}-l-${LIBGOODS_VER}
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" # Skip for merge requests
      when: never
    - if: $CI_COMMIT_REF_NAME

.prod: &prod_definition
  environment:
    name: prod
    url: https://gnome.orr.noaa.gov
  variables:
    API_URL: https://gnome.orr.noaa.gov
    TARGET_ENV: prod
    PYGNOME_VER: production
    LIBGOODS_VER: v2.2.2
    WEBGNOME_API_VER: $CI_COMMIT_TAG
    WEBGNOME_CLIENT_VER: production
    IMAGE_NAME: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}-c-${WEBGNOME_CLIENT_VER}-p-${PYGNOME_VER}-l-${LIBGOODS_VER}
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" # Skip for merge requests
      when: never
    - if: $CI_COMMIT_TAG # only run for tags

Development Build Docker Image:
  <<: *build_definition
  <<: *dev_definition

Production Build Docker Image:
  <<: *build_definition
  <<: *prod_definition

Development Push to ECR and Update Fargate Service:
  dependencies:
    - Development Build Docker Image
  <<: *deploy_definition
  <<: *dev_definition

Production Push to ECR and Update Fargate Service:
  dependencies:
    - Production Build Docker Image
  <<: *deploy_definition
  <<: *prod_definition

Test Built image:
  stage: test
  image:
    name: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA}-c-${WEBGNOME_CLIENT_VER}-p-${PYGNOME_VER}-l-${LIBGOODS_VER}
    entrypoint: ['']
  allow_failure: true
  tags:
    - docker
  script:
    - apt update
    - apt install redis -y
    - redis-server --daemonize yes
    - rm -rf ./location_files
    - ln -s /location_files ./location_files
    - /env/bin/pip install pytest webtest>=2.0 testfixtures
    - /env/bin/pytest --pyargs webgnome_api
  <<: *dev_definition

Test Source:
  stage: test
  tags:
    - docker
  image: registry.orr.noaa.gov/gnome/pygnome:$PYGNOME_VER
  <<: *dev_definition
  script:
    ## We want to get the artifacts from the pygnome compile job, which is
    ## a different CI pipeline altogether where:
    ## - $PYGNOME_PROJECT_ID is the pygnome project id (defined as literal)
    ## - $CI_COMMIT_BRANCH is the branch
    ## - compile_pygnome is the job_name
    - >
    #   curl
    #   "https://gitlab.orr.noaa.gov/api/v4/projects/${PYGNOME_PROJECT_ID}/jobs/artifacts/${CI_COMMIT_BRANCH}/download?job=compile_pygnome&&job_token=${CI_JOB_TOKEN}"
    #   --output artifacts.zip
    # - ls -l artifacts.zip || echo "no file artifacts.zip"
    # - unzip artifacts.zip "py_gnome/*" -d py_gnome || echo "can't read
    #   artifacts.zip"
    # - head artifacts.zip

    - apt-get update
    - apt-get install -y redis
    - redis-server --daemonize yes

    # get libgoods
    - git clone --depth 1 -b $LIBGOODS_VER
      https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.orr.noaa.gov/gnome/libgoods.git

    # install all the requirements
    - conda install -y python=$PYTHON_VER --file conda_requirements.txt --file
      conda_requirements_test.txt --file libgoods/conda_requirements.txt --file
      /pygnome/py_gnome/conda_requirements.txt

    - pushd libgoods && pip install . && popd
    - pip install .
    - python location_files/compile_locations.py
    - python location_files/test_locations.py
    - conda env export > webgnome_api/views/deployed_environment.yaml
    - cd webgnome_api/tests && pytest
