FROM registry.orr.noaa.gov/system-admins/container-registry/sidecar-traefik/sidecar-traefik:1.1.2 AS certfarm

FROM nginx:latest

COPY --from=certfarm /etc/ssl/certs/orr.noaa.gov.key /etc/ssl/certs/orr.noaa.gov.key
COPY --from=certfarm /etc/ssl/certs/orr.noaa.gov.crt /etc/ssl/certs/orr.noaa.gov.crt
COPY ./data/*	/usr/share/nginx/html/py_gnome_testdata/