[workspace]
authors = ["Chris Barker <Chris.Barker@noaa.gov>"]
channels = ["conda-forge"]
name = "webgnomeapi"
platforms = ["win-64", "linux-64", "osx-arm64", "osx-64"]
version = "0.1.0"

[pypi-options]
no-build-isolation = true

# [feature.run.pypi-dependencies]
# gnome = {path = "wheelhouse/gnome-1.1.19.dev0-cp313-cp313-macosx_10_13_x86_64.whl"}

# [feature.build-gnome.dependencies]
# cython= "3.*"
# pip = "*"
# # setuptools>=62  # older versions uses different build dirs
# # setuptools-scm>=6.2
# python-build = "*"
# cmake  = "*"
# ninja  = "*"
# scikit-build-core = ">=0.9.9"


[dependencies]
python = "3.13.*"
awesome-slugify = "*"
colander = "<2"
progressbar = "*"
psutil = "*"
python-dateutil = "*"
pyzmq = "*"
numpy = ">=2.0,<3"  #  works with numpy 1 and 2
scipy = "*"
gsw = "*"
netCDF4 = "*"
trimesh = "*"
geojson = "*"
geopandas = "*"
mapbox_earcut = "*"
pyogrio = "*"
pyproj = "*"
shapely = ">=2.1.2"
gridded = ">=0.7.5,<0.8"
pynucos = ">=3.4.0"
py_gd = ">=2.3.3"
adios_db = ">=1.2.7"
xarray-subset-grid = "*"
requests = "*"
s3fs = "*"
pandas = "*"
pyyaml = "*"
siphon = "*"
fiona = "*"
cfgrib = "*"
zarr = "<3"
setuptools = "<81"  #  need old version for Pyramid and pkg_resources
regex = "*"
pyramid = ">=2,<3"
paste = "*"
pastedeploy = ">=2.0"
pyramid_log = "*"
pyramid_session_redis = "*"
cornice = ">=3.4"
ujson = "*"
docutils = "*"
htmlmin = "*"
jsmin = "*"
gitpython = "*"
waitress = "*"
pycparser = "*"
gevent = "*"
python-socketio = "*"
gevent-websocket = "*"
redis-py = "=4.6.0"
google-api-python-client = "*"
google-auth = "*"
google-auth-httplib2 = "*"
google-auth-oauthlib = "*"
pytest = "*"
webtest = ">=2.0"
testfixtures = "*"

# [feature.run.pypi-dependencies]
# gnome = {path = "wheelhouse/gnome-1.1.19.dev0-cp313-cp313-macosx_10_13_x86_64.whl"}

[feature.dev.dependencies]
# needed to build pygnome
cython="3.*"
pip = "*"
setuptools= ">=62"
gitpython = "*"
python-build = "*"
cmake = "*"
ninja = "*"
scikit-build-core = ">=0.9.9"

# need redis server for Mac
[target.osx-64.dependencies]
redis-server = "*"

[target.osx-arm64.dependencies]
redis-server = "*"

[feature.dev.pypi-dependencies]
webgnome-api = { path = ".", editable = true }
# pygnome = {path = "../pygnome/py_gnome/", editable = true }
libgoods = {path = "../libgoods/", editable = true }

[environments]
default = { solve-group = "default" }
dev = ["dev"]
# run = ["run"]
# build-gnome = ["build-gnome"]


[tasks]
build = "pip install --no-build-isolation ."
