'''Generate a Gmail OAuth2 token'''
import sys
import io
import logging
from argparse import ArgumentParser, RawTextHelpFormatter
from urllib.parse import parse_qs, urlparse

import ujson

from google_auth_oauthlib.flow import Flow


logger = logging.getLogger(__name__)

GEN_TOKEN_DESCRIPTION=(
'''Generate a Gmail OAuth2 token:
    This is a utility script to allocate oauth credentials.  It reads the
    OAUTH json config and generates an OAuth2 credentials JSON structure
    that contains a refreshed token.
    
    The token generated is very long lived, so my understanding is you only
    need to do it once.
      
    In WebGnomeAPI, the resulting token is to be injected as a secret and
    used for sending email.  The precise method of injecting TBD.
'''
)

gen_token_argp = ArgumentParser(description=GEN_TOKEN_DESCRIPTION,
                                formatter_class=RawTextHelpFormatter)
gen_token_argp.add_argument(
    '--config',
    default='./client_secrets.json',
    help=('Specify a client secrets *.json file that has been '
          'generated by the Google Cloud Console Clients page. '
          'If not specified, the default is to use "./client_secrets.json" ')
)
gen_token_argp.add_argument(
    '--token-out',
    default='./credentials_out.json',
    help=('Specify a path to write the generated JSON credentials.  '
          'If not specified, the default is to use "./credentials_out.json"')
)
gen_token_argp.add_argument(
    '--log_level', default='INFO',
    choices=['DEBUG', 'INFO', 'WARNING', 'ERROR', 'CRITICAL',
             'debug', 'info', 'warning', 'error', 'critical'],
    help='Set the logging level.  The default is INFO')


def generate_token_cmd(argv=sys.argv):
    """
    The Paste command entrypoint for gmail credentials generation utility.
    """
    # Python 3 has made stderr buffered, so we have to fix it
    sys.stderr = io.TextIOWrapper(sys.stderr.detach().detach(),
                                  write_through=True)

    args = gen_token_argp.parse_args(argv[1:])
    logging.basicConfig(level=getattr(logging, args.log_level.upper()))

    try:
        generate_token(args.config, args.token_out)
    except Exception:
        print(f'{generate_token.__name__}() FAILED\n')
        raise


def generate_token(client_secret_filename, credentials_out_filename):
    """
    Generate an OAuth2 credentials JSON structure that contains a
    refreshed token.
    """
    print(f'{client_secret_filename=}, {credentials_out_filename=}')

    client_secret = get_client_secret_json(client_secret_filename)
    web_cfg = get_web_config_json(client_secret)
    redirect_uri = get_redidrect_uri_from_cfg(web_cfg)

    # scopes = ["https://mail.google.com/"]
    scopes = ["https://www.googleapis.com/auth/gmail.send"]

    flow = Flow.from_client_config(client_secret, scopes=scopes)
    flow.redirect_uri = redirect_uri

    auth_url, _state = get_flow_authorization(flow)

    print(f'Open this URL in a browser and authorize: {auth_url}')

    code = get_authorization_code()

    flow.fetch_token(code=code)
    creds = flow.credentials

    if not creds.refresh_token:
        logger.warning(
            'Warning: refresh_token is missing.  If this is not the '
            'first authorization, you may need to revoke prior grants '
            'or use a new user and try again.'
        )

    token_data = ujson.loads(creds.to_json())

    with open(credentials_out_filename, "w", encoding="utf-8") as outfile:
        ujson.dump(token_data, outfile, indent=2, sort_keys=True)
    print(f'Wrote credentials JSON to {credentials_out_filename}')


def get_client_secret_json(client_secret_filename):
    """
    Get the client secret json structure from the json file.
    """
    try:
        with open(client_secret_filename, encoding="utf-8") as file:
            client_secret = ujson.load(file)
    except FileNotFoundError:
        logger.error("File not found at %s", client_secret_filename)
        raise
    except IOError as e:
        logger.error("An I/O error occurred: %s", e)
        raise
    else:
        return client_secret


def get_web_config_json(client_secret):
    """Get the web configuration from our client secret json struct"""
    try:
        web_cfg = client_secret["web"]
    except KeyError:
        logger.error('client secret JSON file must contain a '
                        'top-level "web" key')
        raise

    return web_cfg

def get_redidrect_uri_from_cfg(web_cfg):
    """Get the redirect_uri"""
    redirect_uri = web_cfg.get("redirect_uris", [None])[0]

    if redirect_uri is None:
        raise ValueError("No redirect URI available in configuration.")

    return redirect_uri


def get_flow_authorization(flow):
    """
    This is just to better document the parameters you pass into the
    authorization_url() function.
    """
    return flow.authorization_url(
        # Recommended, enable offline access so that you can refresh an access token without
        # re-prompting the user for permission. Recommended for web server apps.
        access_type='offline',
        # Optional, set prompt to 'consent' will prompt the user for consent
        prompt='consent',
        # Optional, enable incremental authorization. Recommended as a best practice.
        include_granted_scopes='true',
        # Optional, if your application knows which user is trying to authenticate, it can use this
        # parameter to provide a hint to the Google Authentication Server.
        # right now this is hardcoded for debugging, we will do better soon.
        login_hint='james.makela@gmail.com',
    )


def get_authorization_code():
    """
    Manual input step: get either the authorization code or the url that is
    provided after the successful google authorization step.
    """
    print('After approval, paste either the full redirect URL or the '
          '"code" parameter value.')

    code_input = input("Code or redirect URL: ").strip()
    if not code_input:
        raise SystemExit("No authorization code provided")

    if code_input.startswith("http://") or code_input.startswith("https://"):
        parsed = urlparse(code_input)
        params = parse_qs(parsed.query)
        if "code" not in params:
            raise SystemExit("URL does not include a 'code' query parameter")
        code = params["code"][0]
    else:
        code = code_input

    return code
