- hosts: all
  become: true

  tasks:
    - name: ensure the network is setup
      docker_network:
        name: webgnome_net
        state: present
        attachable: true

    - name: log into ORR gitlab registry
      docker_login:
        registry_url: "{{ lookup('ansible.builtin.env', 'CI_REGISTRY') }}"
        username: "{{ lookup('ansible.builtin.env', 'CI_REGISTRY_USER') }}"
        password: "{{ lookup('ansible.builtin.env', 'CI_REGISTRY_PASSWORD') }}"

    - name: ensure redis server is running and available
      docker_swarm_service:
        name: redis
        image: redis:7.2.4
        pull: true
        networks:
          - name: webgnome_net

    - name: ensure the proxy is running
      docker_swarm_service:
        name: proxy
        image: registry.orr.noaa.gov/system-admins/container-registry/sidecar-traefik/sidecar-traefik:1.1.2
        networks:
          - name: webgnome_net
        labels:
          traefik.enable: 'true'
          traefik.docker.network:
          traefik.http.routers.cc-mobile.entrypoints: websecure
          traefik.http.routers.cc-mobile.rule:
            'Host(`m.cameochemicals.noaa.gov`,
            `m.cameochemicals-stage.orr.noaa.gov`, `m.cameochemicals.nos.noaa`)'
          traefik.http.routers.cc-mobile.service: cc-mobile
          traefik.http.services.cc-mobile.loadbalancer.server.scheme: http
          traefik.http.services.cc-mobile.loadbalancer.server.port: '8080'
          traefik.http.routers.cc-mobile.middlewares: security-headers

    - name: ensure cameo chemicals container is running
      docker_container:
        name: cameo-chemicals
        state: started
        restart: true
        restart_policy: 'unless-stopped'
        env:
          CC_LIVE: 'true'
          CC_DEPLOY: 'prod'
          CC_LAYOUT: 'main'
          CC_MOBILE: 'false'
        image:
          "{{ lookup('ansible.builtin.env', 'CI_REGISTRY_IMAGE')
          }}/cameo-chemicals:{{ lookup('ansible.builtin.env',
          'CI_COMMIT_REF_NAME') }}"
        pull: true
        networks:
          - name: cameo-public
        labels:
          traefik.http.middlewares.redirect-cc-old-api.redirectregex.regex: '^https://cameochemicals.*noaa.gov/update/?(.*)$'
          traefik.http.middlewares.redirect-cc-old-api.redirectregex.replacement: 'https://cameo.noaa.gov/api/cameochemicals/$1'
          traefik.http.middlewares.redirect-marplot-old-api.redirectregex.regex: '^https://cameochemicals.*noaa.gov/marplot/?(.*)$'
          traefik.http.middlewares.redirect-marplot-old-api.redirectregex.replacement: 'https://cameo.noaa.gov/api/marplot/$1'
          traefik.enable: 'true'
          traefik.docker.network: cameo-public
          traefik.http.routers.cameo-chemicals.entrypoints: websecure
          traefik.http.routers.cameo-chemicals.rule:
            'Host(`cameochemicals.noaa.gov`,
            `cameochemicals-stage.orr.noaa.gov`, `cameochemicals.nos.noaa`)'
          traefik.http.routers.cameo-chemicals.service: cameo-chemicals
          traefik.http.services.cameo-chemicals.loadbalancer.server.scheme: http
          traefik.http.services.cameo-chemicals.loadbalancer.server.port: '8080'
          traefik.http.routers.cameo-chemicals.middlewares: security-headers,redirect-cc-old-api,redirect-marplot-old-api
