[program:client]
# Note that py-autoreload can be removed in production :-) 
#command=uvicorn erma_project.asgi:application --uds /tmp/asgi.sock --lifespan off
command=/bin/bash -c 'pserve /config_files/api_config.ini'
directory=/webgnomeclient
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
priority=300

