[program:aws_mirror_matrix]
command=bash /scripts/aws-mirror-matrix-to-efs.sh
autostart=false
autorestart=false
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
directory=/
startsecs=0