# Supervisord config file used in ERMA production.
# This can be run like so:
# CONFIG=supervisord-celery.conf sudo venv/bin/supervisord --configuration config_files/supervisord.conf

[supervisord]
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0

stderr_logfile=/dev/stdout
stderr_logfile_maxbytes=0

logfile=/dev/stdout
logfile_maxbytes=0

redirect_stderr=true
pidfile=/var/run/supervisord
loglevel=warn
# In production don't log to the local logfiles.
#logfile_backups=1
nodaemon=true
user=root


[include]
# Load only the config that is defined for this particular instance - since in a container
# we only want to start the one process, not all of them.
files=%(ENV_SUPERVISOR_CONFIG)s